#!/usr/bin/env bash

#!/usr/bin/env bash
set -o errexit # set -e
set -o pipefail
scriptdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
script_file=$(basename "$0")

trovedir="$scriptdir/output"
tmpdir="$scriptdir/tmp"
mkdir -p "$trovedir"
mkdir -p "$tmpdir"

echo "CSV --> json, this might take a while"
${scriptdir}/transform.sh

one_json_file="${trovedir}/amazon-Test.json"
cat "${one_json_file}" | jq . >/dev/null